// <auto-generated />
using System;
using EMC.DB;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EMC.DB.Migrations
{
    [DbContext(typeof(AppDb))]
    [Migration("20251104014742_MigrationFileName")]
    partial class MigrationFileName
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.32");

            modelBuilder.Entity("EMC.DB.Alarm", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Sqlite:Autoincrement", true);

                    b.Property<string>("Action")
                        .HasColumnType("TEXT")
                        .HasMaxLength(512);

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT")
                        .HasMaxLength(512);

                    b.Property<int>("Enable")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(1);

                    b.Property<DateTime>("LastRaisedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Level")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasMaxLength(128);

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("LastRaisedAt");

                    b.HasIndex("Name");

                    b.ToTable("Alarms");
                });

            modelBuilder.Entity("EMC.DB.AlarmHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AlarmId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Level")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdateTime")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UpdateTime");

                    b.HasIndex("AlarmId", "UpdateTime");

                    b.ToTable("AlarmHistories");
                });

            modelBuilder.Entity("EMC.DB.Motion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Axis")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasMaxLength(16);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasMaxLength(100);

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Motions");
                });

            modelBuilder.Entity("EMC.DB.MotionPosition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("CurrentLocation")
                        .HasColumnType("REAL");

                    b.Property<int>("CurrentSpeed")
                        .HasColumnType("REAL");

                    b.Property<double>("MaximumLocation")
                        .HasColumnType("REAL");

                    b.Property<int>("MaximumSpeed")
                        .HasColumnType("INTEGER");

                    b.Property<double>("MinimumLocation")
                        .HasColumnType("REAL");

                    b.Property<int>("MinimumSpeed")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MotionId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasMaxLength(100);

                    b.HasKey("Id");

                    b.HasIndex("MotionId", "Name")
                        .IsUnique();

                    b.ToTable("MotionPositions");
                });

            modelBuilder.Entity("EMC.DB.PowerPMac", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Ip")
                        .HasColumnType("TEXT")
                        .HasMaxLength(64);

                    b.Property<string>("Name")
                        .HasColumnType("TEXT")
                        .HasMaxLength(64);

                    b.HasKey("Id");

                    b.ToTable("PowerPMac");
                });

            modelBuilder.Entity("EMC.DB.PowerPMacMotion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AlarmLevel")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("EmergencyEnable")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<bool>("EmergencyLevel")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EncoderInputMethod")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("EncoderReverse")
                        .HasColumnType("INTEGER");

                    b.Property<double>("HomeAccelerate1")
                        .HasColumnType("REAL");

                    b.Property<double>("HomeAccelerate2")
                        .HasColumnType("REAL");

                    b.Property<double>("HomeDecelerate1")
                        .HasColumnType("REAL");

                    b.Property<double>("HomeDecelerate2")
                        .HasColumnType("REAL");

                    b.Property<int>("HomeMode1")
                        .HasColumnType("INTEGER");

                    b.Property<int>("HomeMode2")
                        .HasColumnType("INTEGER");

                    b.Property<double>("HomeOffset")
                        .HasColumnType("REAL");

                    b.Property<double>("HomeVelocity1")
                        .HasColumnType("REAL");

                    b.Property<double>("HomeVelocity2")
                        .HasColumnType("REAL");

                    b.Property<double>("HomeVelocity3")
                        .HasColumnType("REAL");

                    b.Property<bool>("InPositionEnable")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<bool>("InPositionLevel")
                        .HasColumnType("INTEGER");

                    b.Property<double>("InPositionWidth")
                        .HasColumnType("REAL");

                    b.Property<bool>("IsEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.Property<string>("Maker")
                        .HasColumnType("TEXT")
                        .HasMaxLength(32);

                    b.Property<double>("MaxVelocity")
                        .HasColumnType("REAL");

                    b.Property<int>("MotorNo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasMaxLength(64);

                    b.Property<bool>("NegativeLimitLevel")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NegativeLimitMode")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("OriginLevel")
                        .HasColumnType("INTEGER");

                    b.Property<double>("PositionError")
                        .HasColumnType("REAL");

                    b.Property<bool>("PositiveLimitLevel")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PositiveLimitMode")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PowerPMacId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PulseOutputMethod")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Ratio")
                        .HasColumnType("REAL");

                    b.Property<bool>("ServoLevel")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ServoOffOnEmergencyEnable")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<bool>("SoftLimitEnable")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<double>("SoftNegativeLimit")
                        .HasColumnType("REAL");

                    b.Property<double>("SoftPositiveLimit")
                        .HasColumnType("REAL");

                    b.Property<int>("SpeedMode")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Type")
                        .HasColumnType("TEXT")
                        .HasMaxLength(32);

                    b.HasKey("Id");

                    b.HasIndex("PowerPMacId");

                    b.ToTable("PowerPMacMotion");
                });

            modelBuilder.Entity("EMC.DB.Recipe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Sqlite:Autoincrement", true);

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("strftime('%Y-%m-%dT%H:%M:%fZ','now')");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("IsActive")
                        .IsUnique()
                        .HasName("UX_Recipes_OnlyOneActive")
                        .HasFilter("IsActive = 1");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Recipes");
                });

            modelBuilder.Entity("EMC.DB.RecipeParam", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Sqlite:Autoincrement", true);

                    b.Property<string>("Description")
                        .HasColumnType("TEXT")
                        .HasMaxLength(500);

                    b.Property<string>("Maximum")
                        .HasColumnType("TEXT");

                    b.Property<string>("Minimum")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasMaxLength(100);

                    b.Property<int>("RecipeId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UnitId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ValueTypeId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("RecipeId");

                    b.HasIndex("UnitId");

                    b.HasIndex("ValueTypeId");

                    b.ToTable("RecipeParam");
                });

            modelBuilder.Entity("EMC.DB.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Sqlite:Autoincrement", true);

                    b.Property<string>("Description")
                        .HasColumnType("TEXT")
                        .HasMaxLength(200);

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasMaxLength(100);

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasMaxLength(200);

                    b.Property<int>("Rank")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("EMC.DB.RoleManageRole", b =>
                {
                    b.Property<int>("ManagerRoleId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TargetRoleId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("CanManage")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.HasKey("ManagerRoleId", "TargetRoleId");

                    b.HasIndex("TargetRoleId");

                    b.ToTable("RoleManageRole");
                });

            modelBuilder.Entity("EMC.DB.RoleScreenAccess", b =>
                {
                    b.Property<int>("RoleId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ScreenId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Granted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.HasKey("RoleId", "ScreenId");

                    b.HasIndex("RoleId")
                        .HasName("IX_RoleScreenAccess_RoleId");

                    b.HasIndex("ScreenId")
                        .HasName("IX_RoleScreenAccess_ScreenId");

                    b.ToTable("RoleScreenAccess");
                });

            modelBuilder.Entity("EMC.DB.Screen", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasMaxLength(100);

                    b.Property<int>("DisplayOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<bool>("IsEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasMaxLength(100);

                    b.Property<string>("Path")
                        .HasColumnType("TEXT")
                        .HasMaxLength(200);

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Screens");
                });

            modelBuilder.Entity("EMC.DB.Unit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Sqlite:Autoincrement", true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Symbol")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Unit");
                });

            modelBuilder.Entity("EMC.DB.ValueTypeDef", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Sqlite:Autoincrement", true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("ValueType");
                });

            modelBuilder.Entity("EMC.DB.AlarmHistory", b =>
                {
                    b.HasOne("EMC.DB.Alarm", null)
                        .WithMany()
                        .HasForeignKey("AlarmId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EMC.DB.MotionPosition", b =>
                {
                    b.HasOne("EMC.DB.Motion", "Motion")
                        .WithMany("Positions")
                        .HasForeignKey("MotionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EMC.DB.PowerPMacMotion", b =>
                {
                    b.HasOne("EMC.DB.PowerPMac", "PowerPMac")
                        .WithMany("MotionList")
                        .HasForeignKey("PowerPMacId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EMC.DB.RecipeParam", b =>
                {
                    b.HasOne("EMC.DB.Recipe", "Recipe")
                        .WithMany("Params")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EMC.DB.Unit", "Unit")
                        .WithMany()
                        .HasForeignKey("UnitId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .IsRequired();

                    b.HasOne("EMC.DB.ValueTypeDef", "ValueType")
                        .WithMany()
                        .HasForeignKey("ValueTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("EMC.DB.RoleManageRole", b =>
                {
                    b.HasOne("EMC.DB.Role", "Manager")
                        .WithMany("ManageTargets")
                        .HasForeignKey("ManagerRoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EMC.DB.Role", "Target")
                        .WithMany("ManagedBy")
                        .HasForeignKey("TargetRoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EMC.DB.RoleScreenAccess", b =>
                {
                    b.HasOne("EMC.DB.Role", "Role")
                        .WithMany("ScreenAccesses")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EMC.DB.Screen", "Screen")
                        .WithMany("AccessBy")
                        .HasForeignKey("ScreenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
